// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJqv2JvECaVPGC2GYL1Hztsz96aNqTC-Q',
    appId: '1:52688105199:web:82fe5ce7323714fff3b51a',
    messagingSenderId: '52688105199',
    projectId: 'spend-sneak',
    authDomain: 'spend-sneak.firebaseapp.com',
    storageBucket: 'spend-sneak.appspot.com',
    measurementId: 'G-08Y3X9YX9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmKBYNKF_QUJOab7zvjM8oFaIKWmy1i9o',
    appId: '1:52688105199:android:4b1101495504e990f3b51a',
    messagingSenderId: '52688105199',
    projectId: 'spend-sneak',
    storageBucket: 'spend-sneak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFqP_Hqv5dZx_PQgH5yOxwn_3869XgY14',
    appId: '1:52688105199:ios:d9a9748ada9583aaf3b51a',
    messagingSenderId: '52688105199',
    projectId: 'spend-sneak',
    storageBucket: 'spend-sneak.appspot.com',
    iosBundleId: 'com.example.expeness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFqP_Hqv5dZx_PQgH5yOxwn_3869XgY14',
    appId: '1:52688105199:ios:27c9b542b2619033f3b51a',
    messagingSenderId: '52688105199',
    projectId: 'spend-sneak',
    storageBucket: 'spend-sneak.appspot.com',
    iosBundleId: 'com.example.expeness.RunnerTests',
  );
}
